import { Tool, HistoryEntry } from '../types';

export const DEMO_DATA: { tools: Tool[]; history: HistoryEntry[] } = {
  tools: [
    {
      id: 't-101',
      name: 'VHM-Bohrer Ø6,0 mm lang',
      category: 'Bohrer',
      typ: 'VHM-Bohrer',
      status: 'verfügbar',
      quantity: 5,
      diameter: 6.0,
      shank: 6.0,
      length: 57.0,
      flutes: 2,
      coating: 'TiAlN',
      material: 'VHM',
      manufacturer: 'Gühring',
      sku: '5511-6.000',
      magazine: 'T12',
      holder: 'HSK-A63',
      zLength: 142.5,
      coolant: 'Innenkühlung',
      machine: 'Hermle C40',
      location: 'Schublade A1',
      notes: 'vc=120 m/min, fz=0.08 mm, für Edelstahl 1.4301',
      updatedAt: '2026-09-15T09:42:00.000Z',
      updatedBy: 'G. Palacios',
      icon: '🔩'
    },
    {
      id: 't-102',
      name: 'VHM-Schaftfräser Ø10,0 mm Z4',
      category: 'Fräser',
      typ: 'VHM-Fräser',
      status: 'in Maschine',
      quantity: 3,
      diameter: 10.0,
      shank: 10.0,
      length: 72.0,
      flutes: 4,
      coating: 'AlCrN',
      material: 'VHM',
      manufacturer: 'Sandvik Coromant',
      sku: '1P240-1000-XB',
      magazine: 'T04',
      holder: 'SK40',
      zLength: 110.2,
      coolant: 'Innen- & Außenkühlung',
      machine: 'DMG Mori DMU 50',
      location: 'Schublade B2',
      notes: 'Schruppen & Schlichten Stahl bis 1100 N/mm²',
      updatedAt: '2026-09-14T15:20:00.000Z',
      updatedBy: 'B. Daniel',
      icon: '🌀'
    },
    {
      id: 't-103',
      name: 'Planfräskopf Ø50 mm 45°',
      category: 'Planfräser',
      typ: 'Planfräser',
      status: 'verfügbar',
      quantity: 2,
      diameter: 50.0,
      shank: 22.0,
      length: 40.0,
      flutes: 5,
      coating: 'CVD beschichtet',
      material: 'Stahlkörper',
      manufacturer: 'Seco Tools',
      sku: 'R220.69-0050-09-5',
      magazine: 'T18',
      holder: 'HSK-A63 Aufsteckdorn',
      zLength: 95.0,
      coolant: 'Innenkühlung',
      machine: 'Hermle C40',
      location: 'Regal C-03',
      notes: 'Wendeplatten SEEX 09T3 AFTN',
      updatedAt: '2026-09-13T11:15:00.000Z',
      updatedBy: 'F. Klotz',
      icon: '⏹️'
    },
    {
      id: 't-104',
      name: 'Gewindebohrer M8 6H HSS-E-PM',
      category: 'Gewindewerkzeuge',
      typ: 'Gewindebohrer',
      status: 'verfügbar',
      quantity: 1, // Niedriger Bestand
      diameter: 8.0,
      shank: 8.0,
      length: 90.0,
      flutes: 3,
      coating: 'TiN',
      material: 'HSS-E-PM',
      manufacturer: 'Emuge Franken',
      sku: 'B0201100.0080',
      magazine: 'T08',
      holder: 'ER32 Spannzange',
      zLength: 125.4,
      coolant: 'Außenkühlung',
      machine: 'Matsuura VX-1000',
      location: 'Schublade G1',
      notes: 'Für Durchgangsloch in Vergütungsstahl',
      updatedAt: '2026-09-15T08:10:00.000Z',
      updatedBy: 'G. Palacios',
      icon: '🔧'
    },
    {
      id: 't-105',
      name: 'VHM-Radiusfräser Ø4,0 mm R2,0',
      category: 'Fräser',
      typ: 'Radiusfräser',
      status: 'verschlissen',
      quantity: 0, // Kritischer Bestand / Leer
      diameter: 4.0,
      shank: 6.0,
      length: 50.0,
      flutes: 2,
      coating: 'DLC beschichtet',
      material: 'VHM',
      manufacturer: 'Hoffmann Garant',
      sku: '207120-4',
      magazine: 'T22',
      holder: 'HSK-A63 Schrumpffutter',
      zLength: 130.0,
      coolant: 'Minimalmengenschmierung (MMS)',
      machine: 'Hermle C40',
      location: 'Schublade B4',
      notes: 'Nachschleifen erforderlich!',
      updatedAt: '2026-09-12T16:45:00.000Z',
      updatedBy: 'B. Daniel',
      icon: '⚪'
    },
    {
      id: 't-106',
      name: 'Kegelsenker 90° Ø16,5 mm',
      category: 'Senker',
      typ: 'Kegelsenker',
      status: 'verfügbar',
      quantity: 4,
      diameter: 16.5,
      shank: 10.0,
      length: 60.0,
      flutes: 3,
      coating: 'TiAlN',
      material: 'HSS-E',
      manufacturer: 'Ruko',
      sku: '102116E',
      magazine: 'T02',
      holder: 'Weldon Ø10',
      zLength: 88.0,
      coolant: 'Außenkühlung',
      machine: 'DMG Mori DMU 50',
      location: 'Schublade A3',
      notes: 'Für Senkungen M8 DIN 74 Form A',
      updatedAt: '2026-09-10T14:20:00.000Z',
      updatedBy: 'G. Palacios',
      icon: '🔺'
    }
  ],
  history: [
    {
      id: 'h-1',
      timestamp: '2026-09-15T09:42:00.000Z',
      userName: 'G. Palacios',
      action: 'Bestand erhöht',
      toolName: 'VHM-Bohrer Ø6,0 mm lang',
      toolId: 't-101',
      quantity: '+2 Stk.',
      machine: 'Hermle C40',
      details: 'Wareneingang 2x Guhring Bohrer eingelagert in Schublade A1'
    },
    {
      id: 'h-2',
      timestamp: '2026-09-15T08:10:00.000Z',
      userName: 'G. Palacios',
      action: 'Entnahme',
      toolName: 'Gewindebohrer M8 6H HSS-E-PM',
      toolId: 't-104',
      quantity: '-1 Stk.',
      machine: 'Matsuura VX-1000',
      details: 'Rüstvorgang Bauteil Gehäuse Serie 42'
    },
    {
      id: 'h-3',
      timestamp: '2026-09-14T15:20:00.000Z',
      userName: 'B. Daniel',
      action: 'In Maschine gerüstet',
      toolName: 'VHM-Schaftfräser Ø10,0 mm Z4',
      toolId: 't-102',
      quantity: '1 Stk.',
      machine: 'DMG Mori DMU 50',
      details: 'Auf Magazinplatz T04 eingewechselt'
    },
    {
      id: 'h-4',
      timestamp: '2026-09-13T11:15:00.000Z',
      userName: 'F. Klotz',
      action: 'Plattenwechsel',
      toolName: 'Planfräskopf Ø50 mm 45°',
      toolId: 't-103',
      quantity: '5 Platten',
      machine: 'Hermle C40',
      details: 'Schneidkanten gewendet nach 140 min Schnittzeit'
    },
    {
      id: 'h-5',
      timestamp: '2026-09-12T16:45:00.000Z',
      userName: 'B. Daniel',
      action: 'Status geändert',
      toolName: 'VHM-Radiusfräser Ø4,0 mm R2,0',
      toolId: 't-105',
      quantity: '0 Stk.',
      machine: 'Hermle C40',
      details: 'Auf Verschlissen gesetzt – Ausbruch an Schneide 1'
    }
  ]
};

export const DEMO_RECORD = DEMO_DATA;
